-- ============================================================
-- Simulador de Cabeamento — SEED v2
-- Popula todas as 14 missões, pinos, perguntas e opções
-- Execute DEPOIS do db-schema-v2.sql
-- ============================================================
USE simulador_cabeamento;

-- Limpa antes de inserir (safe re-run)
SET FOREIGN_KEY_CHECKS=0;
TRUNCATE question_options;
TRUNCATE questions;
TRUNCATE mission_cola;
TRUNCATE mission_lookup;
TRUNCATE mission_pins;
TRUNCATE mission_sides;
TRUNCATE missions;
SET FOREIGN_KEY_CHECKS=1;

-- ============================================================
-- MISSÕES
-- ============================================================
INSERT INTO missions (id,sort_order,title,short_desc,intro,type,position_prefix,pin_question_text) VALUES
('m1',1,'Cabo direto — padrão T568B','Ponta A e ponta B idênticas',
 'O cabo mais comum de rede: liga PC ao switch, switch ao roteador etc. As duas pontas seguem a mesma ordem de pinos.',
 'pins','P','Qual fio vai no pino {n}?'),

('m2',2,'Cabo direto — padrão T568A','Mesma ideia, outro padrão de cores',
 'Mesmo tipo de cabo direto, mas seguindo o padrão T568A — usado por algumas normas residenciais e governamentais dos EUA.',
 'pins','P','Qual fio vai no pino {n}?'),

('m3',3,'Cabo crossover','Uma ponta em cada padrão',
 'Usado para ligar dois dispositivos iguais direto (PC a PC, switch a switch). A ponta A segue T568B — a ponta B você monta em T568A.',
 'pins','P','Qual fio vai no pino {n}?'),

('m4',4,'Cabo console (rollover Cisco)','Pino espelhado ponta a ponta',
 'Cabo chato usado pra acessar a porta de console de switches e roteadores Cisco. A regra é o espelhamento: pino 1 vira pino 8, 2 vira 7, e assim por diante.',
 'pins','P','Qual fio vai no pino {n}?'),

('m5',5,'Patch panel — documentação do rack','Achar a porta certa pela etiqueta',
 'Depois de crimpar, o cabo chega no patch panel do rack. Cada porta tem uma etiqueta com o código do cabo. Sua tarefa: dada a sala que precisa de suporte, achar a porta certa lendo o painel.',
 'lookup','P','Qual fio vai no pino {n}?'),

('m6',6,'PoE — Power over Ethernet','Como a energia viaja pelo cabo de rede',
 'Alguns equipamentos (câmera IP, telefone VoIP, access point) recebem energia elétrica pelo mesmo cabo de rede, sem fonte separada.',
 'mcq','P','Qual fio vai no pino {n}?'),

('m7',7,'Categorias de cabo','Cat5e, Cat6, Cat6a e por aí vai',
 'Nem todo cabo de rede é igual. A categoria determina a frequência suportada, a velocidade máxima e até que distância isso se mantém confiável.',
 'mcq','P','Qual fio vai no pino {n}?'),

('m8',8,'Diagnóstico com testador','Ler o wiremap e achar o defeito',
 'O testador de cabo mostra qual pino de um lado acende no outro lado (o wiremap). Saber ler esse resultado é o que diferencia quem só crimpa de quem resolve problema em campo.',
 'mcq','P','Qual fio vai no pino {n}?'),

('m9',9,'Switch e rack','Acesso, trunk, uplink e cascateamento',
 'Última parada do cobre: entender como os switches se conectam entre si e distribuem VLANs.',
 'mcq','P','Qual fio vai no pino {n}?'),

('m10',10,'Fibra óptica — código de cores','12 fibras, 12 cores padronizadas',
 'Dentro de um cabo multifibra, cada fibra segue uma sequência de cores padronizada (TIA/EIA-598-C), pra identificar rapidamente qual é qual sem precisar testar uma por uma.',
 'pins','F','Qual a cor da fibra número {n}?'),

('m11',11,'Tipos de conector de fibra','SC, LC, ST, FC e outros',
 'Assim como RJ45 no cobre, existem padrões de conectores em fibra. Cada um tem vantagens, tamanho e uso específico.',
 'mcq','P','Qual fio vai no pino {n}?'),

('m12',12,'Emenda de fibra','Fusão vs mecânica — quando usar cada uma',
 'Dois fios de fibra precisam ser unidos? Existem dois caminhos: fusão (permanente, melhor performance) ou emenda mecânica (rápida, mas com perda).',
 'mcq','P','Qual fio vai no pino {n}?'),

('m13',13,'Monomodo vs Multimodo','Quando usar cada tipo de fibra',
 'Duas famílias de fibra cobrem 99% do mercado: monomodo (singlemode), pra longa distância, e multimodo, pra curta distância e prédios.',
 'mcq','P','Qual fio vai no pino {n}?'),

('m14',14,'Atenuação e perda de sinal','dB, orçamento de link e OTDR',
 'Luz viaja pela fibra, mas perde força — cada km, cada conector, cada emenda custa dB. Calcular o orçamento de perda e verificar com OTDR é como um técnico garante que a fibra vai funcionar.',
 'mcq','P','Qual fio vai no pino {n}?');

-- ============================================================
-- SIDES E PINOS
-- ============================================================

-- M1: T568B ponta única
INSERT INTO mission_sides (id,mission_id,side_order,label,is_quiz) VALUES
(1,'m1',0,'Ponta A e Ponta B (iguais)',1);
INSERT INTO mission_pins (side_id,pin_order,name,type,color_a,color_b) VALUES
(1,1,'Branco/Laranja','striped','#f2f2ee','#e2782f'),
(1,2,'Laranja','solid','#e2782f',NULL),
(1,3,'Branco/Verde','striped','#f2f2ee','#4c9a5a'),
(1,4,'Azul','solid','#3f6fb0',NULL),
(1,5,'Branco/Azul','striped','#f2f2ee','#3f6fb0'),
(1,6,'Verde','solid','#4c9a5a',NULL),
(1,7,'Branco/Marrom','striped','#f2f2ee','#7a5233'),
(1,8,'Marrom','solid','#7a5233',NULL);

-- M2: T568A ponta única
INSERT INTO mission_sides (id,mission_id,side_order,label,is_quiz) VALUES
(2,'m2',0,'Ponta A e Ponta B (iguais)',1);
INSERT INTO mission_pins (side_id,pin_order,name,type,color_a,color_b) VALUES
(2,1,'Branco/Verde','striped','#f2f2ee','#4c9a5a'),
(2,2,'Verde','solid','#4c9a5a',NULL),
(2,3,'Branco/Laranja','striped','#f2f2ee','#e2782f'),
(2,4,'Azul','solid','#3f6fb0',NULL),
(2,5,'Branco/Azul','striped','#f2f2ee','#3f6fb0'),
(2,6,'Laranja','solid','#e2782f',NULL),
(2,7,'Branco/Marrom','striped','#f2f2ee','#7a5233'),
(2,8,'Marrom','solid','#7a5233',NULL);

-- M3: Crossover — lado A fixo (T568B), lado B quiz (T568A)
INSERT INTO mission_sides (id,mission_id,side_order,label,is_quiz) VALUES
(3,'m3',0,'Ponta A — T568B (referência)',0),
(4,'m3',1,'Ponta B — T568A',1);
INSERT INTO mission_pins (side_id,pin_order,name,type,color_a,color_b) VALUES
(3,1,'Branco/Laranja','striped','#f2f2ee','#e2782f'),(3,2,'Laranja','solid','#e2782f',NULL),
(3,3,'Branco/Verde','striped','#f2f2ee','#4c9a5a'),(3,4,'Azul','solid','#3f6fb0',NULL),
(3,5,'Branco/Azul','striped','#f2f2ee','#3f6fb0'),(3,6,'Verde','solid','#4c9a5a',NULL),
(3,7,'Branco/Marrom','striped','#f2f2ee','#7a5233'),(3,8,'Marrom','solid','#7a5233',NULL),
(4,1,'Branco/Verde','striped','#f2f2ee','#4c9a5a'),(4,2,'Verde','solid','#4c9a5a',NULL),
(4,3,'Branco/Laranja','striped','#f2f2ee','#e2782f'),(4,4,'Azul','solid','#3f6fb0',NULL),
(4,5,'Branco/Azul','striped','#f2f2ee','#3f6fb0'),(4,6,'Laranja','solid','#e2782f',NULL),
(4,7,'Branco/Marrom','striped','#f2f2ee','#7a5233'),(4,8,'Marrom','solid','#7a5233',NULL);

-- M4: Console Cisco — lado A fixo, lado B espelhado
INSERT INTO mission_sides (id,mission_id,side_order,label,is_quiz) VALUES
(5,'m4',0,'Ponta A — fixa (referência)',0),
(6,'m4',1,'Ponta B — espelhada',1);
INSERT INTO mission_pins (side_id,pin_order,name,type,color_a,color_b) VALUES
(5,1,'Preto','solid','#2b2b2b',NULL),(5,2,'Marrom','solid','#7a5233',NULL),
(5,3,'Vermelho','solid','#c23b3b',NULL),(5,4,'Laranja','solid','#e2782f',NULL),
(5,5,'Amarelo','solid','#e0c23a',NULL),(5,6,'Verde','solid','#4c9a5a',NULL),
(5,7,'Azul','solid','#3f6fb0',NULL),(5,8,'Roxo','solid','#7a4fa0',NULL),
-- espelhado (8→1)
(6,1,'Roxo','solid','#7a4fa0',NULL),(6,2,'Azul','solid','#3f6fb0',NULL),
(6,3,'Verde','solid','#4c9a5a',NULL),(6,4,'Amarelo','solid','#e0c23a',NULL),
(6,5,'Laranja','solid','#e2782f',NULL),(6,6,'Vermelho','solid','#c23b3b',NULL),
(6,7,'Marrom','solid','#7a5233',NULL),(6,8,'Preto','solid','#2b2b2b',NULL);

-- M10: Fibra — 12 cores TIA-598-C
INSERT INTO mission_sides (id,mission_id,side_order,label,is_quiz) VALUES
(7,'m10',0,'Sequência de 12 fibras (padrão TIA-598-C)',1);
INSERT INTO mission_pins (side_id,pin_order,name,type,color_a,color_b) VALUES
(7,1,'Azul','solid','#3f6fb0',NULL),(7,2,'Laranja','solid','#e2782f',NULL),
(7,3,'Verde','solid','#4c9a5a',NULL),(7,4,'Marrom','solid','#7a5233',NULL),
(7,5,'Cinza','solid','#8a8f93',NULL),(7,6,'Branco','solid','#f2f2ee',NULL),
(7,7,'Vermelho','solid','#c23b3b',NULL),(7,8,'Preto','solid','#2b2b2b',NULL),
(7,9,'Amarelo','solid','#e0c23a',NULL),(7,10,'Violeta','solid','#7a4fa0',NULL),
(7,11,'Rosa','solid','#d8779c',NULL),(7,12,'Água','solid','#4fb8b0',NULL);

-- ============================================================
-- PATCH PANEL (M5)
-- ============================================================
INSERT INTO mission_lookup (mission_id,port_number,room_name,cable_id) VALUES
('m5',1,'Sala 101','B-101'),('m5',2,'Sala 204','B-204'),
('m5',3,'Recepção','B-REC'),('m5',4,'Sala 102','B-102'),
('m5',5,'TI — Servidor','B-SRV'),('m5',6,'Sala 305','B-305'),
('m5',7,'Sala 103','B-103'),('m5',8,'Copa','B-COPA'),
('m5',9,'Sala 201','B-201'),('m5',10,'Diretoria','B-DIR'),
('m5',11,'Sala 302','B-302'),('m5',12,'Wi-Fi AP — 2º andar','B-AP2');

-- ============================================================
-- COLA (mcq missions)
-- ============================================================
INSERT INTO mission_cola (mission_id,sort_order,note) VALUES
('m6',1,'Modo A → energia nos pinos 1, 2, 3 e 6 (mesmos pares de dados)'),
('m6',2,'Modo B → energia nos pinos 4, 5, 7 e 8 (pares reserva)'),
('m6',3,'802.3af (PoE) → até 15,4 W na fonte'),
('m6',4,'802.3at (PoE+) → até 30 W na fonte'),
('m6',5,'802.3bt (PoE++) → até 90–100 W, usando os 4 pares'),
('m6',6,'PSE = quem fornece energia · PD = quem recebe'),

('m7',1,'Cat5e → até 1 Gbps, 100 MHz'),
('m7',2,'Cat6 → 1 Gbps em 100 m, ou 10 Gbps só até ~55 m, 250 MHz'),
('m7',3,'Cat6a → 10 Gbps em 100 m, 500 MHz — padrão atual pra 10G'),
('m7',4,'Cat7 → exige conector GG45/TERA (não é RJ45 puro)'),
('m7',5,'Cat8 → até 40 Gbps, só até ~30 m — uso entre switches em data center'),
('m7',6,'UTP = sem blindagem · STP/FTP = blindado (precisa aterrar a malha)'),

('m8',1,'Wiremap normal → pino X sempre acende o pino X do outro lado'),
('m8',2,'Par invertido → dois fios do mesmo par trocados de posição'),
('m8',3,'Aberto (open) → pino não acende nada do outro lado (rompimento)'),
('m8',4,'Curto (short) → dois fios que não deveriam se tocar aparecem ligados'),
('m8',5,'Split pair → wiremap parece normal, mas usa fios de pares diferentes = crosstalk'),
('m8',6,'Um crossover intencional NÃO é defeito — é o padrão esperado'),

('m9',1,'Porta de acesso → carrega 1 VLAN, vai pro dispositivo final (PC, impressora)'),
('m9',2,'Porta trunk → carrega várias VLANs marcadas com 802.1Q, entre switches'),
('m9',3,'Uplink → liga o switch a outro switch ou ao roteador, é a espinha dorsal'),
('m9',4,'Cascateamento → switch ligado a switch pra ganhar mais portas'),
('m9',5,'STP (Spanning Tree Protocol) evita loops quando há caminhos redundantes'),
('m9',6,'Switch gerenciável permite VLAN/trunk/monitoramento; não gerenciável só encaminha tráfego'),

('m11',1,'SC (Subscriber Connector) — push-pull, versátil, uso geral'),
('m11',2,'LC (Lucent Connector) — pequeno, duplex, alta densidade de portas'),
('m11',3,'ST (Straight Tip) — meio vintage, ainda visto em instalações antigas'),
('m11',4,'FC (Ferrule Connector) — robusto, rosca, muito usado em high-reliability'),
('m11',5,'APC (Angled Physical Contact) — ângulo 8°, reduz reflexão'),
('m11',6,'UPC (Ultra Physical Contact) — contato plano, comum em datacenters'),

('m12',1,'Fusão — fusiona dois núcleos com arco elétrico, perda 0,1–0,3 dB, permanente'),
('m12',2,'Mecânica — alinha os núcleos mecanicamente, perda 0,3–0,8 dB, reversível'),
('m12',3,'Fusão exige emendadora (máquina cara)'),
('m12',4,'Mecânica é rápida e portátil, ideal pra emergência ou teste temporário'),
('m12',5,'Emendadora mede perda automaticamente após fusão'),
('m12',6,'Singlemode requer alinhamento muito mais preciso que multimodo'),

('m13',1,'Multimodo — núcleo 50 µm, até ~2 km, datacenter/prédio'),
('m13',2,'Monomodo — núcleo 8–10 µm, até 100+ km, telecom/ISP'),
('m13',3,'Dispersão modal (multimodo) limita distância; monomodo não tem esse problema'),
('m13',4,'OM3 e OM4 → 10G até 400 m; OM1 → até 2 km em 10G'),
('m13',5,'Monomodo G.652 → padrão telecomunicações globais'),
('m13',6,'Laser em multimodo requer maior banda que LED'),

('m14',1,'Atenuação = perda por km de fibra, ~0,2 dB/km em 1550 nm (monomodo)'),
('m14',2,'Conectores = ~0,5 dB cada (ou ~0,3 em APC)'),
('m14',3,'Emendas mecânicas = 0,3–0,8 dB; fusão = 0,1–0,3 dB'),
('m14',4,'Orçamento de perda = máximo de dB que o link aguenta de ponta a ponta'),
('m14',5,'OTDR = radar de fibra, mostra atenuação e faults'),
('m14',6,'Margem de segurança = orçamento total − perda medida (deve ser >3 dB)');


-- ============================================================
-- PERGUNTAS
-- ============================================================
INSERT INTO questions (id,mission_id,sort_order,question_text,context_text) VALUES
(1,'m6',1,'Quantos pares de fios existem dentro de um cabo Ethernet comum?','Fundamento antes de falar de PoE'),
(2,'m6',2,'No Modo A do PoE, a energia passa pelos mesmos pares usados para dados em redes 10/100. Quais pinos são esses?','Modo A — Alternative A'),
(3,'m6',3,'No Modo B do PoE, a energia passa pelos pares que sobram em redes 10/100. Quais pinos são esses?','Modo B — Alternative B'),
(4,'m6',4,'O padrão original de PoE, IEEE 802.3af, fornece até quanto de potência na fonte?','802.3af'),
(5,'m6',5,'O PoE+ (IEEE 802.3at) aumenta a potência disponível para até quanto?','802.3at'),
(6,'m6',6,'O padrão IEEE 802.3bt (PoE++), usando os 4 pares ao mesmo tempo, chega a entregar até quanto?','802.3bt'),
(7,'m6',7,'Qual sigla identifica o equipamento que FORNECE energia PoE?','Quem fornece x quem recebe'),
(8,'m6',8,'Qual sigla identifica o equipamento que RECEBE a energia (câmera IP, telefone, access point)?','Quem fornece x quem recebe'),
(9,'m7',1,'Qual é a categoria mínima recomendada hoje pra suportar Gigabit Ethernet de forma confiável?','Categoria mínima pra Gigabit'),
(10,'m7',2,'Qual a frequência máxima suportada pelo Cat6?','Frequência do Cat6'),
(11,'m7',3,'Até quantos metros o Cat6 consegue entregar 10 Gbps de forma confiável?','Limite do Cat6 em 10G'),
(12,'m7',4,'Qual categoria garante 10 Gbps em cabos de até 100 metros?','10G em distância cheia'),
(13,'m7',5,'Cabos blindados (STP/FTP) protegem contra interferência, mas exigem qual cuidado extra?','Cuidado com cabo blindado'),
(14,'m7',6,'Por que o Cat7 é pouco usado no mercado, apesar da alta performance?','Limitação prática do Cat7'),
(15,'m7',7,'O Cat8 entrega até 40 Gbps em qual distância máxima?','Cat8 — uso em data center'),
(16,'m7',8,'Cabo UTP costuma ser suficiente pra qual cenário?','Quando usar UTP'),
(17,'m8',1,'O testador mostra: 1→1 2→2 3→3 4→4 5→5 6→6 7→7 8→8. O que isso indica?','Leitura do wiremap'),
(18,'m8',2,'O testador mostra: 1→2 2→1 3→3 4→4 5→5 6→6 7→7 8→8. O que isso indica?','Leitura do wiremap'),
(19,'m8',3,'O testador mostra: pino 4 não acende nada do outro lado. O que isso indica?','Leitura do wiremap'),
(20,'m8',4,'Os pinos 3 e 6 acendem juntos no receptor. O que isso indica?','Leitura do wiremap'),
(21,'m8',5,'Wiremap com continuidade perfeita, mas fios de pares diferentes foram usados juntos. Qual problema isso causa?','Falha que o testador simples não vê'),
(22,'m8',6,'O testador mostra: 1→3 2→6 3→1 6→2 (demais normais). Isso é um defeito?','Nem todo wiremap diferente é falha'),
(23,'m8',7,'Nenhum dos 8 pinos acende do outro lado. O que verificar primeiro?','Primeiro passo do diagnóstico'),
(24,'m8',8,'Qual a diferença entre cabo aberto (open) e curto (short)?','Conceito open x short'),
(25,'m9',1,'O que é uma porta de acesso (access port) num switch?','Porta de acesso'),
(26,'m9',2,'O que é uma porta trunk?','Porta trunk'),
(27,'m9',3,'Pra que serve a porta uplink de um switch?','Uplink'),
(28,'m9',4,'O que é cascateamento de switches?','Cascateamento'),
(29,'m9',5,'Qual o risco de cascatear switches em excesso?','Risco do cascateamento excessivo'),
(30,'m9',6,'O que evita loops de rede quando existem caminhos redundantes entre switches?','Prevenção de loop'),
(31,'m9',7,'Qual a diferença entre switch gerenciável e não gerenciável?','Gerenciável x não gerenciável'),
(32,'m9',8,'Qual prática evita um ponto único de falha na conexão entre switch de acesso e núcleo?','Evitando ponto único de falha'),
(33,'m11',1,'Qual conector de fibra usa mecanismo push-pull e é versátil pra uso geral?','Conector versátil'),
(34,'m11',2,'Qual conector é muito menor que o SC e permite alta densidade de portas?','Conector compacto'),
(35,'m11',3,'O conector ST é menos usado hoje. Em qual contexto ainda é encontrado?','ST — uso legado'),
(36,'m11',4,'Qual conector usa rosca pra fixação e é conhecido por ser robusto?','Conector robusto'),
(37,'m11',5,'O que significa APC num conector de fibra?','APC'),
(38,'m11',6,'Qual a diferença prática entre UPC e APC?','UPC x APC'),
(39,'m11',7,'Por que conectores LC estão se tornando mais comuns em datacenters modernos?','Popularidade do LC'),
(40,'m11',8,'Qual conector é frequentemente encontrado com terminação APC em redes de telecom?','APC + conector'),
(41,'m12',1,'Qual é a principal vantagem da fusão sobre a emenda mecânica?','Vantagem da fusão'),
(42,'m12',2,'Qual é a principal vantagem da emenda mecânica sobre a fusão?','Vantagem da mecânica'),
(43,'m12',3,'O que é uma emendadora de fusão?','Equipamento de fusão'),
(44,'m12',4,'Qual a perda típica de uma emenda mecânica bem feita?','Perda mecânica'),
(45,'m12',5,'Qual a perda típica de uma fusão bem feita?','Perda da fusão'),
(46,'m12',6,'Em qual cenário você escolheria emenda mecânica em vez de fusão?','Quando escolher mecânica'),
(47,'m12',7,'O que a emendadora mede automaticamente após fusionar as fibras?','Medição pós-fusão'),
(48,'m12',8,'Por que a fusão em singlemode exige alinhamento mais preciso que em multimodo?','Precisão por tipo de fibra'),
(49,'m13',1,'Qual tipo de fibra tem núcleo de ~50 µm e suporta múltiplos caminhos de luz?','Definição de multimodo'),
(50,'m13',2,'Qual tipo de fibra tem núcleo de ~8–10 µm e suporta um único caminho de luz?','Definição de monomodo'),
(51,'m13',3,'Qual é a distância máxima típica para fibra multimodo em enlaces 10G?','Distância do multimodo'),
(52,'m13',4,'Qual é a distância máxima típica para fibra monomodo?','Distância do monomodo'),
(53,'m13',5,'O que é dispersão modal e por que ela limita a distância do multimodo?','Dispersão modal'),
(54,'m13',6,'Por que monomodo não sofre dispersão modal?','Vantagem do monomodo'),
(55,'m13',7,'Qual é o padrão global de fibra monomodo mais comum em telecom?','Padrão monomodo global'),
(56,'m13',8,'Você precisa ligar dois prédios distantes 50 km. Qual tipo de fibra é obrigatória?','Escolha por distância'),
(57,'m14',1,'Qual é a atenuação típica de fibra monomodo em 1550 nm?','Atenuação de fibra'),
(58,'m14',2,'Quantos dB perde um link de 50 km de fibra monomodo (sem conectores/emendas)?','Cálculo simples de atenuação'),
(59,'m14',3,'Qual a perda típica de um conector SC/UPC bem encaixado?','Perda de conector'),
(60,'m14',4,'Um conector APC tem perda menor ou maior que UPC?','APC vs UPC em perda'),
(61,'m14',5,'O que é orçamento de perda de um link óptico?','Orçamento de perda'),
(62,'m14',6,'Um link tem orçamento de 20 dB e perda medida de 15 dB. Qual a margem de segurança?','Cálculo de margem'),
(63,'m14',7,'Qual margem de segurança é considerada mínima aceitável num projeto de fibra?','Margem mínima segura'),
(64,'m14',8,'O que é um OTDR?','Conceito OTDR');

INSERT INTO question_options (question_id,option_text,is_correct) VALUES
(1,'4 pares (8 fios)',1),
(1,'2 pares (4 fios)',0),
(1,'8 pares (16 fios)',0),
(1,'1 par (2 fios)',0),
(2,'Pinos 1, 2, 3 e 6',1),
(2,'Pinos 4, 5, 7 e 8',0),
(2,'Pinos 1, 2, 4 e 5',0),
(2,'Todos os 8 pinos',0),
(3,'Pinos 4, 5, 7 e 8',1),
(3,'Pinos 1, 2, 3 e 6',0),
(3,'Pinos 3, 4, 5 e 6',0),
(3,'Apenas o pino 1',0),
(4,'Até 15,4 W',1),
(4,'Até 30 W',0),
(4,'Até 60 W',0),
(4,'Até 90 W',0),
(5,'Até 30 W',1),
(5,'Até 15,4 W',0),
(5,'Até 60 W',0),
(5,'Até 100 W',0),
(6,'Até 90–100 W',1),
(6,'Até 15,4 W',0),
(6,'Até 30 W',0),
(6,'Até 7 W',0),
(7,'PSE — Power Sourcing Equipment',1),
(7,'PD — Powered Device',0),
(7,'UPS — fonte externa',0),
(7,'Splitter passivo',0),
(8,'PD — Powered Device',1),
(8,'PSE — Power Sourcing Equipment',0),
(8,'Injetor PoE',0),
(8,'Patch panel',0),
(9,'Cat5e',1),
(9,'Cat5',0),
(9,'Cat3',0),
(9,'Cat6a',0),
(10,'250 MHz',1),
(10,'100 MHz',0),
(10,'500 MHz',0),
(10,'600 MHz',0),
(11,'Até 55 m',1),
(11,'Até 100 m',0),
(11,'Até 10 m',0),
(11,'Não suporta 10 Gbps',0),
(12,'Cat6a',1),
(12,'Cat5e',0),
(12,'Cat6',0),
(12,'Cat3',0),
(13,'Aterramento correto da malha',1),
(13,'Curvar o cabo em 90°',0),
(13,'Usar conector RJ11',0),
(13,'Instalar sem canaleta',0),
(14,'Exige conectores especiais (GG45/TERA), não RJ45 padrão',1),
(14,'É mais barato que o Cat6',0),
(14,'Não suporta Gigabit',0),
(14,'Só funciona com fibra óptica',0),
(15,'Até 30 m',1),
(15,'Até 100 m',0),
(15,'Até 300 m',0),
(15,'Até 1 km',0),
(16,'Ambiente comercial ou residencial comum, sem muita interferência',1),
(16,'Ao lado de motores industriais grandes',0),
(16,'Dentro de um quadro elétrico de alta tensão',0),
(16,'Em ambientes com muita EMI',0),
(17,'Cabo saudável, sem falhas',1),
(17,'Par invertido',0),
(17,'Cabo aberto',0),
(17,'Curto-circuito',0),
(18,'Par invertido (fios 1 e 2 trocados)',1),
(18,'Cabo saudável',0),
(18,'Cabo aberto no pino 1',0),
(18,'Curto-circuito entre 1 e 2',0),
(19,'Cabo aberto (rompimento) no pino 4',1),
(19,'Par invertido',0),
(19,'Curto-circuito',0),
(19,'Cabo saudável',0),
(20,'Curto-circuito entre os pinos 3 e 6',1),
(20,'Par invertido',0),
(20,'Cabo aberto',0),
(20,'Cabo saudável',0),
(21,'Split pair — gera interferência (crosstalk) mesmo com continuidade OK',1),
(21,'Curto-circuito',0),
(21,'Cabo aberto',0),
(21,'Nenhum problema',0),
(22,'Não — é o resultado esperado de um cabo crossover',1),
(22,'Sim — par invertido',0),
(22,'Sim — curto-circuito',0),
(22,'Sim — cabo aberto',0),
(23,'Conector mal encaixado ou cabo rompido em algum ponto',1),
(23,'Trocar o switch imediatamente',0),
(23,'É sempre defeito de fábrica',0),
(23,'Reiniciar o roteador sempre resolve',0),
(24,'Aberto = nenhum sinal passa; curto = dois fios que não deveriam se tocar estão conectados',1),
(24,'Os dois termos significam a mesma coisa',0),
(24,'Aberto é sempre pior que curto',0),
(24,'Curto só acontece em cabo de fibra',0),
(25,'Porta que entrega uma única VLAN a um dispositivo final',1),
(25,'Porta que carrega todas as VLANs ao mesmo tempo',0),
(25,'Porta exclusiva para PoE',0),
(25,'Porta que só funciona em fibra',0),
(26,'Porta que carrega várias VLANs entre switches, usando tags 802.1Q',1),
(26,'Porta que só aceita um dispositivo por vez',0),
(26,'Porta exclusiva de fibra óptica',0),
(26,'Porta usada só para fornecer energia',0),
(27,'Conectar esse switch a outro switch ou ao roteador, formando a espinha dorsal da rede',1),
(27,'Conectar impressoras e computadores',0),
(27,'Fornecer energia extra via PoE',0),
(27,'Servir apenas de porta console',0),
(28,'Ligar um switch a outro switch pra aumentar o número de portas disponíveis',1),
(28,'Trocar switches em produção sem desligar a rede',0),
(28,'Ligar dois switches usando apenas fibra óptica',0),
(28,'Um defeito de configuração de VLAN',0),
(29,'Aumento de latência e maior chance de loop de rede',1),
(29,'Redução do consumo de energia',0),
(29,'Nenhum risco, é sempre seguro',0),
(29,'Melhora automática da velocidade',0),
(30,'Spanning Tree Protocol (STP)',1),
(30,'PoE',0),
(30,'VLAN Tagging sozinho',0),
(30,'DHCP',0),
(31,'O gerenciável permite configurar VLANs, trunk e monitoramento; o não gerenciável só encaminha tráfego',1),
(31,'O não gerenciável é sempre mais caro',0),
(31,'Só o não gerenciável suporta PoE',0),
(31,'Não existe diferença prática',0),
(32,'Uplinks redundantes, ligando a dois equipamentos diferentes',1),
(32,'Usar sempre uma única porta uplink',0),
(32,'Desligar o STP para simplificar a rede',0),
(32,'Conectar todos os PCs direto no roteador',0),
(33,'SC (Subscriber Connector)',1),
(33,'LC (Lucent Connector)',0),
(33,'ST (Straight Tip)',0),
(33,'FC (Ferrule Connector)',0),
(34,'LC (Lucent Connector)',1),
(34,'SC',0),
(34,'ST',0),
(34,'FC',0),
(35,'Em instalações antigas, antes que SC/LC se tornassem padrão',1),
(35,'Em todos os datacenters novos',0),
(35,'Exclusivamente em cabos submarinos',0),
(35,'Nunca foi realmente usado na prática',0),
(36,'FC (Ferrule Connector)',1),
(36,'SC',0),
(36,'LC',0),
(36,'ST',0),
(37,'Angled Physical Contact — ponta em ângulo 8°, reduz reflexão de luz',1),
(37,'Advanced Protective Coating',0),
(37,'Automatic Performance Control',0),
(37,'Adaptable Push Connector',0),
(38,'APC tem ponta angulada (8°) e menor perda de reflexão; UPC é plano, mais padrão em datacenter',1),
(38,'Nenhuma diferença',0),
(38,'APC só funciona com monomodo',0),
(38,'APC é para cobre',0),
(39,'Tamanho reduzido permite maior densidade de portas por unidade de rack',1),
(39,'São muito mais baratos que SC',0),
(39,'Só funcionam com fibra de vidro pura',0),
(39,'Foram mandatoriamente adotados por lei',0),
(40,'SC e LC com APC são ambos usados, mas FC/APC é clássico em telecom',1),
(40,'Apenas o ST',0),
(40,'Nenhum conector funciona com APC',0),
(40,'Só o LC nunca usa APC',0),
(41,'Perda muito menor (0,1–0,3 dB) e conexão permanente',1),
(41,'É mais rápida de fazer',0),
(41,'Não precisa de nenhum equipamento',0),
(41,'É mais barata',0),
(42,'Rápida, portátil, reversível — ideal pra emergência ou teste',1),
(42,'Perda menor',0),
(42,'Não exige nenhuma preparação da fibra',0),
(42,'Funciona em ambiente úmido',0),
(43,'Máquina que usa arco elétrico pra fundir os núcleos de duas fibras',1),
(43,'Um tipo de conector SC',0),
(43,'Um testador portátil de fibra',0),
(43,'Sinônimo de OTDR',0),
(44,'0,3–0,8 dB',1),
(44,'0,05–0,1 dB',0),
(44,'5–10 dB',0),
(44,'Praticamente zero',0),
(45,'0,1–0,3 dB',1),
(45,'0,3–0,8 dB',0),
(45,'1–2 dB',0),
(45,'Nenhuma perda',0),
(46,'Emergência/teste rápido, sem acesso a emendadora, ou conexão temporária',1),
(46,'Sempre — é superior em tudo',0),
(46,'Apenas em fibra multimodo',0),
(46,'Nunca — fusão é sempre melhor',0),
(47,'A perda da emenda (em dB) entre os dois núcleos',1),
(47,'A velocidade da luz no cabo',0),
(47,'O tamanho exato do núcleo',0),
(47,'A temperatura ambiente',0),
(48,'Singlemode tem núcleo muito menor (8 µm vs 50 µm), qualquer desalinhamento causa perda grande',1),
(48,'Singlemode é mais cara',0),
(48,'Multimodo não permite fusão',0),
(48,'Não há diferença real',0),
(49,'Fibra multimodo (MMF)',1),
(49,'Fibra monomodo (SMF)',0),
(49,'Fibra plástica',0),
(49,'Fibra de vidro comum',0),
(50,'Fibra monomodo (SMF)',1),
(50,'Fibra multimodo',0),
(50,'Fibra de plástico',0),
(50,'Cabo de cobre blindado',0),
(51,'Depende da classificação: OM3/OM4 até 400 m; OM1 até 2 km',1),
(51,'Máximo de 100 m sem exceção',0),
(51,'Até 50 km',0),
(51,'Ilimitada',0),
(52,'Centenas de quilômetros, até 100+ km sem repetidor',1),
(52,'Apenas 10 m',0),
(52,'Apenas dentro do mesmo prédio',0),
(52,'Máximo 500 m',0),
(53,'Diferentes modos de luz chegam em tempos diferentes, causando alargamento de pulso',1),
(53,'É um tipo de emenda defeituosa',0),
(53,'Significa que o conector está sujo',0),
(53,'Não existe realmente',0),
(54,'Porque suporta apenas um modo (LP01), não há múltiplos caminhos para desalinhar',1),
(54,'Monomodo sofre dispersão sim',0),
(54,'Porque custa mais caro',0),
(54,'Porque usa LED em vez de laser',0),
(55,'G.652 (ou ITU-T G.652)',1),
(55,'OM4',0),
(55,'Cat8',0),
(55,'SMF-28',0),
(56,'Monomodo — multimodo não chega nem perto dessa distância',1),
(56,'Multimodo OM4 consegue',0),
(56,'Cobre e fibra misturados',0),
(56,'Qualquer uma funciona',0),
(57,'~0,2 dB/km',1),
(57,'~0,02 dB/km',0),
(57,'~2 dB/km',0),
(57,'~20 dB/km',0),
(58,'~10 dB (50 km × 0,2 dB/km)',1),
(58,'~50 dB',0),
(58,'~1 dB',0),
(58,'~100 dB',0),
(59,'~0,5 dB',1),
(59,'~0,05 dB',0),
(59,'~5 dB',0),
(59,'~0,05 µm',0),
(60,'Menor — APC (~0,3 dB) reduz reflexão melhor que UPC (~0,5 dB)',1),
(60,'Maior',0),
(60,'É igual',0),
(60,'Depende da marca',0),
(61,'Quantidade máxima de dB que o link pode perder e ainda funcionar',1),
(61,'O preço do projeto em reais',0),
(61,'A distância máxima de um cabo',0),
(61,'A frequência da luz usada',0),
(62,'5 dB',1),
(62,'15 dB',0),
(62,'20 dB',0),
(62,'Zero',0),
(63,'Pelo menos 3 dB',1),
(63,'Nenhuma margem é necessária',0),
(63,'Mínimo 50 dB',0),
(63,'Máximo 1 dB',0),
(64,'Equipamento que funciona como radar de fibra, medindo atenuação e localizando falhas',1),
(64,'Um tipo de conector',0),
(64,'Sinônimo de testador de continuidade',0),
(64,'Uma emendadora de fusão',0);
